// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package wallet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaymentRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid"`
	OrderId              string   `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId"`
	Value                float64  `protobuf:"fixed64,3,opt,name=value,proto3" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentRequest) Reset()         { *m = PaymentRequest{} }
func (m *PaymentRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentRequest) ProtoMessage()    {}
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{0}
}

func (m *PaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentRequest.Unmarshal(m, b)
}
func (m *PaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentRequest.Marshal(b, m, deterministic)
}
func (m *PaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRequest.Merge(m, src)
}
func (m *PaymentRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentRequest.Size(m)
}
func (m *PaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRequest proto.InternalMessageInfo

func (m *PaymentRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PaymentRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *PaymentRequest) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type CompensatePaymentRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid"`
	OrderId              string   `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId"`
	Value                float64  `protobuf:"fixed64,3,opt,name=value,proto3" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompensatePaymentRequest) Reset()         { *m = CompensatePaymentRequest{} }
func (m *CompensatePaymentRequest) String() string { return proto.CompactTextString(m) }
func (*CompensatePaymentRequest) ProtoMessage()    {}
func (*CompensatePaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{1}
}

func (m *CompensatePaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompensatePaymentRequest.Unmarshal(m, b)
}
func (m *CompensatePaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompensatePaymentRequest.Marshal(b, m, deterministic)
}
func (m *CompensatePaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompensatePaymentRequest.Merge(m, src)
}
func (m *CompensatePaymentRequest) XXX_Size() int {
	return xxx_messageInfo_CompensatePaymentRequest.Size(m)
}
func (m *CompensatePaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompensatePaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompensatePaymentRequest proto.InternalMessageInfo

func (m *CompensatePaymentRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CompensatePaymentRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *CompensatePaymentRequest) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*PaymentRequest)(nil), "wallet.PaymentRequest")
	proto.RegisterType((*CompensatePaymentRequest)(nil), "wallet.CompensatePaymentRequest")
	proto.RegisterType((*Response)(nil), "wallet.Response")
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor_b88fd140af4deb6f) }

var fileDescriptor_b88fd140af4deb6f = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4f, 0xcc, 0xc9,
	0x49, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x82, 0xb8, 0xf8,
	0x02, 0x12, 0x2b, 0x73, 0x53, 0xf3, 0x4a, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x04,
	0xb8, 0x98, 0x4b, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x40, 0x4c, 0x21, 0x09,
	0x2e, 0xf6, 0xfc, 0xa2, 0x94, 0xd4, 0x22, 0xcf, 0x14, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x18, 0x57, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x59, 0x81, 0x51, 0x83,
	0x31, 0x08, 0xc2, 0x51, 0x8a, 0xe1, 0x92, 0x70, 0xce, 0xcf, 0x2d, 0x48, 0xcd, 0x2b, 0x4e, 0x2c,
	0x49, 0xa5, 0xba, 0xe9, 0x06, 0x5c, 0x1c, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42,
	0x42, 0x5c, 0x2c, 0xc9, 0xf9, 0x29, 0xa9, 0x60, 0xe3, 0x58, 0x83, 0xc0, 0x6c, 0x90, 0x0d, 0xb9,
	0xc5, 0xe9, 0x50, 0xb3, 0x40, 0x4c, 0xa3, 0x2e, 0x46, 0x2e, 0xb6, 0x70, 0xb0, 0x77, 0x85, 0x4c,
	0xb9, 0xd8, 0xa1, 0x0e, 0x12, 0x12, 0xd3, 0x83, 0x06, 0x08, 0xaa, 0x0b, 0xa5, 0x04, 0x60, 0xe2,
	0x30, 0x5b, 0x94, 0x18, 0x84, 0x3c, 0xb9, 0x04, 0x31, 0x7c, 0x24, 0xa4, 0x00, 0x53, 0x88, 0xcb,
	0xb3, 0xd8, 0x8c, 0x4a, 0x62, 0x03, 0x87, 0xbf, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x2a,
	0x4f, 0x56, 0x8f, 0x01, 0x00, 0x00,
}
