// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: wallet.proto

package wallet

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Wallet service

func NewWalletEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Wallet service

type WalletService interface {
	Payment(ctx context.Context, in *PaymentRequest, opts ...client.CallOption) (*Response, error)
	CompensatePayment(ctx context.Context, in *CompensatePaymentRequest, opts ...client.CallOption) (*Response, error)
}

type walletService struct {
	c    client.Client
	name string
}

func NewWalletService(name string, c client.Client) WalletService {
	return &walletService{
		c:    c,
		name: name,
	}
}

func (c *walletService) Payment(ctx context.Context, in *PaymentRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Wallet.Payment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletService) CompensatePayment(ctx context.Context, in *CompensatePaymentRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Wallet.CompensatePayment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Wallet service

type WalletHandler interface {
	Payment(context.Context, *PaymentRequest, *Response) error
	CompensatePayment(context.Context, *CompensatePaymentRequest, *Response) error
}

func RegisterWalletHandler(s server.Server, hdlr WalletHandler, opts ...server.HandlerOption) error {
	type wallet interface {
		Payment(ctx context.Context, in *PaymentRequest, out *Response) error
		CompensatePayment(ctx context.Context, in *CompensatePaymentRequest, out *Response) error
	}
	type Wallet struct {
		wallet
	}
	h := &walletHandler{hdlr}
	return s.Handle(s.NewHandler(&Wallet{h}, opts...))
}

type walletHandler struct {
	WalletHandler
}

func (h *walletHandler) Payment(ctx context.Context, in *PaymentRequest, out *Response) error {
	return h.WalletHandler.Payment(ctx, in, out)
}

func (h *walletHandler) CompensatePayment(ctx context.Context, in *CompensatePaymentRequest, out *Response) error {
	return h.WalletHandler.CompensatePayment(ctx, in, out)
}
